version: 2.1

# Include references
!include references.yaml

# Include jobs
!include jobs.yaml

executors:
  base:
    docker:
      - image: cimg/base:stable

# Include parameters
!include parameters.yaml

# Include workflows
!include workflows.yaml
