executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  project_one:
    executor: base
    steps:
      - run: 
          command: |
            echo "project one"
  project_two: 
    executor: base
    steps:
      - run: 
          command: |
            echo "project two" 
  project_three: 
    executor: base
    steps:
      - run: 
          command: |
            echo "project three"
  all_projects: 
    executor: base
    steps:
      - run: 
          command: |
            echo "all"
