references:
  - &build-1
    when: 
      or: 
        - << pipeline.parameters.project-one >>
        - << pipeline.parameters.run-them-all >> 
    jobs:
      - project_one
  - &build-2
    when: 
      or: 
        - << pipeline.parameters.project-two >>
        - << pipeline.parameters.run-them-all >>     
    jobs:
      - project_two
